### ISSUE TITLE
Mismatched number of rows during X dataframe calculation

### ISSUE THREAD

**Issue by PoLabs** [Displayr/flipTextAnalysis#2]
Is any part of the code removing words? I tried playing around with the na.rm=T/F as well as blanks.as.missing, but there's still only z scores for 100 or so less words.
```
text.to.analyze <- PN.df$terms
Xstopwords <- c("amp", "will", "just")
# Converting the text to a vector
text.to.analyze <- as.character(text.to.analyze)

# Extracting the words from the text
library(flipTextAnalysis)
options <- GetTextAnalysisOptions(phrases = '', extra.stopwords.text = '', replacements.text = '', do.stem = TRUE, do.spell = TRUE)
text.analysis.setup <- InitializeWordBag(text.to.analyze, min.frequency = 5.0, operations = options$operations, manual.replacements = options$replacement.matrix, stoplist = options$stopwords, alphabetical.sort = FALSE, phrases = options$phrases, print.type = switch("Word Frequencies", "Word Frequencies" = "frequencies", "Transformed Text" = "transformations")) 

# Sentiment analysis of the phrases 
phrase.sentiment = SaveNetSentimentScores(text.to.analyze, 
                                          check.simple.suffixes = TRUE, blanks.as.missing = TRUE) 
phrase.sentiment[phrase.sentiment >= 1] = 1
phrase.sentiment[phrase.sentiment <= -1] = -1

# Sentiment analysis of the words
td <- as.matrix(AsTermMatrix(text.analysis.setup, min.frequency = 5.0, sparse = TRUE))
counts <- text.analysis.setup$final.counts 
phrase.word.sentiment <- sweep(td, 1, phrase.sentiment, "*")
phrase.word.sentiment[td == 0] <- NA # Setting missing values to Missing
word.mean <- apply(phrase.word.sentiment,2, FUN = mean, na.rm = TRUE)
word.sd <- apply(phrase.word.sentiment,2, FUN = sd, na.rm = TRUE)
word.n <- apply(!is.na(phrase.word.sentiment),2, FUN = sum, na.rm = TRUE)
word.se <- word.sd / sqrt(word.n)
word.z <- word.mean / word.se
word.z[word.n <= 3 || is.na(word.se)] <- 0        
words <- text.analysis.setup$final.tokens
x <- data.frame(word = words, freq = counts, "Sentiment" = word.mean, "Z-Score" = word.z, Length = nchar(words))
word.data <- x[order(counts, decreasing = TRUE), ]
```
Error in data.frame(word = words, freq = counts, Sentiment = word.mean,  : 
  arguments imply differing number of rows: 1466, 1340

**Comment by chschan** [comment]
There are two problems in the example:
1. The number of rows mismatch stops if you set `min.frequency = 0.0`  in
`text.analysis.setup <- InitializeWordBag(text.to.analyze, min.frequency = 5.0, operations = options$operations, manual.replacements = options$replacement.matrix, stoplist = options$stopwords, alphabetical.sort = FALSE, phrases = options$phrases, print.type = switch("Word Frequencies", "Word Frequencies" = "frequencies", "Transformed Text" = "transformations")) `
(The mismatch occurs because the word has occurred at least 5 times in the raw text, but after creating the wordbag, there are less than 5 text responses (rows of the TermMatrix). Mainly, this is because the word occurs multiple times in a text response). 

2. You are losing z scores because you are using short-circuit operators with vectors. So, the 5th line from the bottom should be changed to
`word.z[word.n <= 3 | is.na(word.se)] <- 0 `
